### PR TITLE
Use horizontal averages to compute Richardson number profile

### LINKED ISSUE #112: Richardson number profile output jumps around and is not smooth
The Richardson number profile in the strong wind case and free convection case doesn't seem to be correct,
https://engaging-web.mit.edu/~alir/lesbrary/6DaySuite/three_layer_constant_fluxes_linear_hr144_Qu0.0e+00_Qb5.0e-08_f1.0e-04_Nh256_Nz128_free_convection/instantaneous_statistics.mp4
https://engaging-web.mit.edu/~alir/lesbrary/6DaySuite/three_layer_constant_fluxes_linear_hr144_Qu7.0e-04_Qb0.0e+00_f1.0e-04_Nh256_Nz128_strong_wind/instantaneous_statistics.mp4
The profile looks very jagged in regions were it should be smooth, and jumps around sometimes.

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #112

### CODE REVIEW

**Comment by glwagner** [comment]
Do we need to launch a 3D kernel for this? I think this is a 1D quantity, eg the ratio between the gradient of the horizontally-averaged buoyancy, and the horizontally averaged shear squared.

The _local, 3D_ Richardson number is also a useful quantity; it's just different from the horizontally-averaged Richardson number that often enters into our parameterizations. Both are useful.

**Comment by ali-ramadhan** [comment]
Hmmm, I guess it will launch a 3D kernel and repeat the same computation for each column. Is there an easy way to launch a 1D kernel?

If not we could merge this PR since the output will now be closer to what is expected without introducing any slowdowns. We would save some computations by launching a 1D kernel but with 50+ diagnostics already being computed I suspect the effect of this one 3D kernel is not large.

> The local, 3D Richardson number is also a useful quantity; it's just different from the horizontally-averaged Richardson number that often enters into our parameterizations. Both are useful.

True that both are useful, but sounds like you don't want to output spatial averages of the local Richardson number? 3D and slice outputs could output the (unaveraged) local Richard number while averages could output the "coarse-grained" Richardson number?

**Comment by glwagner** [comment]
I think for this to do the right thing we have to keep the background fields as is but set `model.velocities` and `model.tracers` to zero somehow?

**Comment by glwagner** [comment]
Oh nevermind, I see how it works in Oceanostics. This might work.

**Review by glwagner — APPROVED** [review]
I think we should add a comment so that users don't get confused --- this object computes an identical quantity at every `i, j`, and then takes the horizontal average of that quantity. So there's a lot of wasteful computation but in the end it should return that quantity as a function of `k` only.

**Comment by glwagner** [comment]
It probably would be nice to raise an issue about this if we do merge it so that we don't forget that it's something we still have to fix.

**Comment by ali-ramadhan** [comment]
I opened a new issue to track this and added a comment to the script.

**Pull request merged**
