### PR TITLE
Change module calls from Buoyancy to BuoyancyModels

### PR DESCRIPTION
**Pull request by tomchor**
Oceananigans recently renamed the module `Buoyancy` to `BuoyancyModels`, which I am just now realizing it's a breaking change.

It seems like you guys haven't been doing this, but since this is a breaking change it might be good to bump the version to 0.1.1.

### CODE REVIEW

**Comment by tomchor** [comment]
Sorry, I forgot to update `Project.jl`. However, this brings me to a question that I can't decide on my own.

The script `src/NearSurfaceTurbulenceModels.jl` uses `VerstappenAnisotropicMinimumDissipation`, which doesn't exist anymore. How should we proceed?

**Comment by glwagner** [comment]
> The script src/NearSurfaceTurbulenceModels.jl uses VerstappenAnisotropicMinimumDissipation, which doesn't exist anymore. How should we proceed?

The object that was once called `VerstappenAnisotropicMinimumDissipation` is now called `AnisotropicMinimumDissipation`.

**Comment by tomchor** [comment]
Sorry, I forgot that was the default AMD SGS model. Just fixed it and now the tests should compile.

**Review by ali-ramadhan — APPROVED** [review]
Thanks @tomchor! Updating to the latest version of Oceananigans.jl should now be pretty easy.

**Pull request merged**
