### PR TITLE
Keep Oceananigans at v0.44.0

### PR DESCRIPTION
**Pull request by ali-ramadhan**
@adelinehillier and I were having issues running the three-layer constant flux example as Oceananigans was set to `#master` in the `Manifest.toml`.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
@glwagner For context I think `compute!(buoyancy)` was complaining that some non-isbits argument made its way into a CUDA kernel, but wasn't sure what could have caused that in v0.44.{1,2}.

**Review by glwagner — APPROVED** [review]
That's odd. Supposedly computations with `BuoyancyField` are tested:

https://github.com/CliMA/Oceananigans.jl/blob/672fa9e06aa071360c0451404a1655ba37869b30/test/test_abstract_operations.jl#L324-L344

what changes were made between 0.44.0 and 0.44.2?

**Review by adelinehillier — APPROVED** [review]

**Comment by adelinehillier** [comment]
I think it was specifically when we were working with 0.44.1 that the error was thrown.

**Comment by glwagner** [comment]
Didn't one of those versions get rid of `adapt_structure` for `OffsetArray`? 

I think the problem is here:

https://github.com/CliMA/Oceananigans.jl/blob/672fa9e06aa071360c0451404a1655ba37869b30/src/Buoyancy/buoyancy_field.jl#L122

I think we just need to call `adapt` on `data`. I'm not sure why the tests don't fail.

**Comment by glwagner** [comment]
Wait, I'm confused. We _are_ calling `adapt` on that line.

**Comment by glwagner** [comment]
Not sure if this is it, but I raised anyways: https://github.com/CliMA/Oceananigans.jl/issues/1233

**Comment by navidcy** [comment]
It's not a compat-related issue in Oceananigans.jl. But I have noticed that here
https://github.com/CliMA/LESbrary.jl/blob/6cfe60cf44031f9357936058f08eed0f1bb5f9fc/Manifest.toml#L720-L723
OffsetArrays v1.3.1 is installed..

**Comment by glwagner** [comment]
> OffsetArrays v1.3.1 is installed..

Isn't this because Oceananigans does not enforce OffsetArrays >1.4?

**Pull request merged**
