### PR TITLE
Adds basic documentation

### PR DESCRIPTION
**Pull request by glwagner**
Starts up some basic documentation. 

I think it'd be great to document the diagnostics / `ComputedField`s that `LESbrary.jl` provides. I also think we can write up a basic explanation of the `LESbrary.jl` methodology for reference and also to encourage some discussion.

### CODE REVIEW

**Comment by glwagner** [comment]
@ali-ramadhan do we need to add a block to https://github.com/CliMA/LESbrary.jl/blob/master/.github/workflows/ci.yml to get the docs to build during CI?

I think we'll also want to create a dedicated repository for doc builds (like `OceananigansDocumentation`) at some point but its not urgent.

**Comment by ali-ramadhan** [comment]
Yes I just took https://github.com/ali-ramadhan/DocumenterCitations.jl/blob/master/.github/workflows/Docs.yml and copied it into this branch.

Should work out of the box but we might need to generate a Documenter key and/or GitHub token.

**Comment by navidcy** [comment]
Should we merge this? Shall I have a look?

**Comment by glwagner** [comment]
I suppose we should!

**Comment by glwagner** [comment]
Stale, let's revisit.

**Pull request closed without merging**
